name: PHP Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wp_user
          MYSQL_PASSWORD: wp_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # specify the PHP version you need
          extensions: mbstring, xml, curl

      - name: Install dependencies
        run: |
          composer install

      - name: Run tests
        run: |
          vendor/bin/phpunit --log-junit tests/logs/junit.xml

      - name: Upload test results
        if: always()  # Ensure this runs regardless of the previous step's outcome
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/logs/junit.xml
