name: PHP Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wp_user
          MYSQL_PASSWORD: wp_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, xml, curl

      - name: Install Composer dependencies
        run: composer install

      - name: Install WordPress Testing Framework
        run: |
          wget -O - https://raw.githubusercontent.com/wp-cli/builds/gh-pages/gh-cli.phar > wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          bin/install-wp-tests.sh wordpress_test wp_user wp_pass mysql:3306

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist
