name: Run PHPUnit Tests

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # specify the PHP version you need
          extensions: mbstring, xml, bcmath, mysqli

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist

